### ISSUE TITLE
Provide copyright/license information for the binary blobs

### ISSUE THREAD

**Issue by yarikoptic** [isolver/ioHub#67]
```
$> ls **/*.deb **/*.dll 
devices/daq/hw/mc/DaqDevInfo.dll        devices/eyetracker/hw/sr_research/eyelink/win32/python26/pylink/SDL.dll                    devices/eyetracker/hw/sr_research/eyelink/win32/python27/pylink/eyelink_core.dll
devices/daq/hw/mc/DaqLib.dll            devices/eyetracker/hw/sr_research/eyelink/win32/python26/pylink/SDL_mixer.dll              devices/eyetracker/hw/sr_research/eyelink/win32/python27/pylink/eyelink_core_graphics.dll
devices/daq/hw/mc/cbi_cal.dll           devices/eyetracker/hw/sr_research/eyelink/win32/python26/pylink/SDL_ttf.dll                devices/eyetracker/hw/sr_research/eyelink/win32/python27/pylink/libogg-0.dll
devices/daq/hw/mc/cbi_node.dll          devices/eyetracker/hw/sr_research/eyelink/win32/python26/pylink/eyelink_core.dll           devices/eyetracker/hw/sr_research/eyelink/win32/python27/pylink/libvorbis-0.dll
devices/daq/hw/mc/cbi_prop.dll          devices/eyetracker/hw/sr_research/eyelink/win32/python26/pylink/eyelink_core_graphics.dll  devices/eyetracker/hw/sr_research/eyelink/win32/python27/pylink/libvorbisfile-3.dll
devices/daq/hw/mc/cbi_test.dll          devices/eyetracker/hw/sr_research/eyelink/win32/python26/pylink/libogg-0.dll               devices/eyetracker/hw/sr_research/eyelink/win32/python27/pylink/msvcr71.dll
devices/daq/hw/mc/cbw32.dll             devices/eyetracker/hw/sr_research/eyelink/win32/python26/pylink/libvorbis-0.dll            devices/eyetracker/hw/sr_research/eyelink/win32/python27/pylink/sdl_gfx.dll
devices/daq/hw/mc/win32/DaqDevInfo.dll  devices/eyetracker/hw/sr_research/eyelink/win32/python26/pylink/libvorbisfile-3.dll        devices/eyetracker/hw/sr_research/eyelink/win32/python27/pylink/smpeg.dll
devices/daq/hw/mc/win32/DaqLib.dll      devices/eyetracker/hw/sr_research/eyelink/win32/python26/pylink/msvcr71.dll                devices/eyetracker/hw/tobii/linux/python26/eyetrackerbrowser_0.0.1-svn12561_i386.deb
devices/daq/hw/mc/win32/cbi_cal.dll     devices/eyetracker/hw/sr_research/eyelink/win32/python26/pylink/sdl_gfx.dll                devices/eyetracker/hw/tobii/linux/python26/libtobii-sdkcore_3.0.2_i386.deb
devices/daq/hw/mc/win32/cbi_node.dll    devices/eyetracker/hw/sr_research/eyelink/win32/python26/pylink/smpeg.dll                  devices/eyetracker/hw/tobii/linux/python26/python-tobii-sdkcore_3.0.2_i386.deb
devices/daq/hw/mc/win32/cbi_prop.dll    devices/eyetracker/hw/sr_research/eyelink/win32/python27/pylink/SDL.dll                    devices/eyetracker/hw/tobii/win32/python26/boost_python-vc90-mt-1_41.dll
devices/daq/hw/mc/win32/cbi_test.dll    devices/eyetracker/hw/sr_research/eyelink/win32/python27/pylink/SDL_mixer.dll              devices/eyetracker/hw/tobii/win32/python26/tobiisdk.dll
devices/daq/hw/mc/win32/cbw32.dll       devices/eyetracker/hw/sr_research/eyelink/win32/python27/pylink/SDL_ttf.dll
```

I am not even sure if all of those are redistributable (i.e. that you are not violating someone's license terms)

**Comment by isolver** [comment]
Good point. 

Overall Jon Pierce has pointed out that unless the source for the DLL is available under a GPL license, it can not technically be included with a project that is GPL'ed. So this basically makes all of the dll's (but maybe the SDL ones) marked for removal from the ioHub project.

However I have received permission from some of the eye tracking vendors to include / redistribute the required DLLs with ioHub so it is easier for an end user to use and so we can ensure the right version of the DLL is being used. 

So one idea would be to make a separate package with installer that adds the non GPLed DLLs to an ioHub install that is on a persons system. This should be opened as a separate issue case I guess. The immediate thing to do because of the valid GPL comment is to remove them all until / if a separate non GPL 'ioHubExtras' project is made.

As a note on the DLL status, regardless of what we do before releasing this version:

1) Measurement Computing DLLs need to be removed; that is a mistake in the git ignore file. DO not have permission to include (have not asked).

2) Tobii DLLs : have been told by Oskar Fajerson @ Tobii that their client DLLs needed for ioHub can be included. So if a separate package for easy DLL install was made, these could be included.

3) SMI DLLs : have been told by Thomas Jablonski @ SMI that their client DLLs needed for ioHub can be included. So if a separate package for easy DLL install was made, these could be included.

4) The SR Research Pylink library has no license specified in the pylink distribution that includes the pylink .pyc files and eyelink DLLs (it is what also redistributes the SDL DLLs), so it is assumed that pylink can be included. Pylink has been included in other open source projects  for years with SRR never complaining it was an issue to my knowledge (and I was Director of Operations at SRR until Feb 1st, 2012.), so this is not a totally ignorance based statement.

Regardless, all DLLs should be removed for now and the idea of making a separate project that makes it easier to get libs on a users system without them having to manually do it and configure their environment etc can be considered when there is time to, for the libs that we have permission to distribute of course.

**Comment by isolver** [comment]
Install docs will also need to be updated to reflect this change.

**Comment by isolver** [comment]
Removed all win dll's for now other than pylink package. Updated install docs accordingly.
